#!/bin/sh /etc/rc.common

START=70
USE_PROCD=1

NRPE_CONFIG="/etc/nrpe.cfg"
NRPE_OPTION="-f -n"

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/nrpe
	procd_append_param command ${NRPE_OPTION} -c ${NRPE_CONFIG}
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
